### ISSUE TITLE
Does not replay landing gear retraction Carenado Mooney M20R v 1.0.3

### ISSUE THREAD

**Issue by jctarvin** [till213/SkyDolly#3] opened 2021-06-20 20:16 UTC
Recorded flight in Sky Dolly and simultaneously in OBS.

In the OBS recording, the gear is retracted just fine. That is expected behavior.
However, the gear never retracts when I play back the Sky Dolly Recording. 

Sky Dolly 0.6.2

Makes it pretty useless for post flight production.

Other than that, I really like your application!! Thanks!

John

**Comment by till213** [comment] 2021-06-21 17:23
I think given your statement that "the gear never retracts when I play back the Sky Dolly Recording" we can take out OBS Studio completely out of the equation (otherwise your statement wouldn't make any sense when you say that the "gear does retract in the screen recording (= video)").

So I understand that when replaying the recording done with Sky Dolly the gear simply doesn't retract (or get lowered again, I assume), correct?

* What do you see in the "Simulation Variables" dialog (press V), under "Handles & Brakes" tab? Does the "Gears" variable properly reflect the expected state (= "Up" or "Down")?
* Does the gear work with other aircrafts?

I guess the problem is that the 3rd party aircraft Carenado Mooney M20R simply uses its own variable ("local variable") and ignores the official SimConect "Gear Handle Position" _simulation variable_.

If that is the case then there is nothing that we can do about it (except to try to convince the authors of the aircraft to properly report and react to changes in the "Gear Handle Position" simulation variable).

Also refer to the existing discussion about the "canopy open" and "tailhook" variables here:

https://forums.flightsimulator.com/t/reading-and-setting-tailhook-position-and-canopy-open/379657

This thread contains also instructions about how you could use the MSFS SDK example app "Simvar Watcher" to verify my above theory (that this 3rd party aircraft ignores "Gear Handle Position"):

* Start FS2020
* Start Simvar Watcher
* Connect with FS2020
* Add "Gear Handle Position" (of type "Boolean") as request variable
* Try to modify its value (either 0 or 1 - best when the aircraft is airborne ;))

Does the aircraft lower/raise the gear accordingly? If no (what I expect in case of the "Carenado Mooney M20R") then you have the confirmation that the aircraft simply ignores that variable.


There is however another scenario: it could be that the aircraft has another "switch or lever" (in the end: a "local variable") which influences the general "Gear Handle Position", by constantly "overwritting" it. That is for example the case with the (payware) Fiat G91: while that aircraft basically reacts to the "Canopy Open" simulation variable it has its own variable (a lever in the cockpit, visually speaking) which constantly "resets" its state. That's exactly the reason why I introduced the "Repeat Values" settings, in the "Replay" tab.

The one setting of interest here is the "Canopy" checkbox, which is enabled by default already (because I don't know of any aircraft as of yet which would work without it). In fact, the entire "Handles & Brakes" group is repeatedly sent (which lowers the hopes already that this would actually help in the case of the Carenado). But it's worth a try:

* Make sure that the "Canopy" checkbox (under "Repeat Values") is enabled
* Re-record a flight, with raising / lowering gear

Does that help?

**Comment by till213** [comment] 2021-06-26 15:40
Hi,

I am closing this issue now since I did not get any further feedback. So I assume that the 3rd party aircraft in question simply does not respond to the corresponding "Gears Position" simulation variable. This could be verified with either another replay tool, or the "SimvarWatcher" example app which comes with the MS Flight Simulator SDK.

Let me know if you find a way to control the gears of the Carenado Mooney via the SimConnect API (e.g. via the SimvarWatcher app)!

**Comment by till213** [comment] 2021-06-28 07:09
I am actually re-opening this issue because I received a similar report about the gear not being lowered/raised with the 3rd party aircraft DC-6.

Sky Dolly currently records and replays the "Gear Handle Position" simulation variable, which represents the state of the "gear handle" in the cockpit. This seems to work with the in-game aircrafts, and several other 3rd party aircrafts (Spitfire, Fiat G.91, Goshawk).

In fact, there are a couple of other "gear" related simulation variables (all "writebale", too: https://docs.flightsimulator.com/html/index.htm#t=Programming_Tools%2FSimVars%2FAircraft_Simulation_Variables.htm)

* GEAR HANDLE POSITION (currently being recorded and replayed)
* GEAR LEFT POSITION (Percent left gear extended)
* GEAR POSITION (Position of landing gear:[index])
* GEAR RIGHT POSITION (Percent right gear extended)

The GEAR POSITION seems interesting (and somewhat redundant to GEAR HANDLE POSITION), so I will experiment with that first. The GEAR LEFT|RIGHT POSITION seem to be used for the actual animation of the gear, but might be worth checking out, too (they might eventually "force" the visible gear to lower/raise).

**Comment by jctarvin** [comment] 2021-06-28 18:42
Hi, Oliver

I downloaded your latest version. It worked with the existing recording, which I obviously had to "load" into the new version. Saving and reloading a newly recorded file has been helpful for me.

Thanks for keeping me posted. I'm enjoying Sky Dolly.

⁣John

**Comment by till213** [comment] 2021-07-12 17:35
Thanks for letting me know that it now seems to work!

As the other reporter (on flightsim.to) also reported that the gear now works (with the PMDG DC-6) I will close this issue for now.

**Closed** 2021-07-12 17:35 UTC

**Comment by jctarvin** [comment] 2021-07-12 20:12
Just used Sky Dolly to record a flight of current Airbus H135. On playback there are lots of artifacts that pop in and out on the skids and various other locations. That may be an H135 issue, but thought I should mention it. Going to try it using Flight Recorder and see if results are the same.

⁣John

**Comment by till213** [comment] 2021-07-18 05:53
„On playback there are lots of artifacts that pop in and out on the skids and various other locations.“

What artifacts? Are we talking about rendering issues aka „graphic glitches“? Those would be definitively out of the realms of Sky Dolly: Sky Dolly merely sends the previously recorded „simulation variables“. The visual rendering is completely up to the simulator respectively the aircraft model.

**Comment by till213** [comment] 2021-07-19 19:05
„ Since it doesn't occur in most aircraft, should I advise the aircraft developer (Hype Performance Group, Airbus H135)?“

First off, are we talking about „graphical glitches“ that only occur during replay? If so, they could be indeed triggered by some SimConnect „set simulation variable“ request (but which one). It is hard to tell, without even knowing what kind of glitches we are talking about (n order to guesstimate what could cause them).

In any case it sounds like an issue with the aircraft itself (given the fact that it only happens with this aircraft, and even reproducible with two replay applications.

You could try and ask the aircraft developer, but they might simply refer you to the replay applications. But it is worth a try. You can try to suggest the developer to try to reproduce the issue with Sky Dolly (or Flight Recorder) - after all it is freely available.

**Comment by jctarvin** [comment] 2021-07-20 01:33
Thanks for your advice, Oliver!! 

⁣John​


-------- Original Message --------

**Comment by till213** [comment] 2023-01-29 14:16
The freshly released **v0.14** has improved support for 3rd-party aircraft, specifically for gears, flaps and spoilers and other controls (but not everything is working perfectly yet, depending on the aircraft and its specific simulation logic).

So you may want to give it another try with the Carenado Mooney M20R.
