### ISSUE TITLE
Logbbok cannot be created / opened

### ISSUE THREAD

**Issue by PhilM5253** [till213/SkyDolly#119] opened 2023-09-09 20:49 UTC
re our previous conversations ...

I am using SD v0.16.3

No - as far as I can see / tell - SD is NOT creating a log file, that I can ever find, in any location, via File Explorer.

What seems to be happening (to my untutored eye) is that SD is running a check to see if there is an existing log file: that would be loaded if present, both to be available for use and to prevent a new, default file being opened which would (?) overwrite the existing file.

On first use, there is no existing log file, and so SD correctly (?) shows an error message that no file exists.

If (?) SD should then create a new, default file for use, is it that next step that is not happening?

And, as said before, I cannot manually create a new file either.
 
In trying to open, create and save a log file, file explorer can never 'see' a *.sdlog file with which to perform any operation.

Is the first, correct (?) error message that no file exists on opening somehow stopping the create / save file actions from working as expected?

As noted in the other issue post, SD IS creating Registry entries on my system: it was that info that was in my screenshot (posted here also for ease of reference): I don't have any idea what the Registry entries should look like or contain, but I thought they might help explain was is / is not happening? 
<img width="734" alt="Screenshot skydolly regedit" src="https://github.com/till213/SkyDolly/assets/144495675/dc1166b3-12b2-45c4-b744-5486a2cf1065">

**Comment by till213** [comment] 2023-09-11 18:39
Apparently "controlled folder access" has more to do with "trusted" vs "untrusted" apps rather than manifest files. Sky Dolly is not "digitally signed" (a digital signing certificate costs hundreds of dollars every other year), so I guess that makes it an "untrusted" app.

Or in other words: there is probably little I can do "in a programmatic way" (by providing a corresponding manifest file, that is).

Also refer to:

https://www.computerworld.com/article/3665694/windows-controlled-folder-access-think-twice-before-deploying.html

So while I will do more research whether I can still make an app "trustworthy" (by providing a proper manifest) I now tend to say that "this is simply by design": if you enable "controlled folder access" (that might be enabled by default on Windows 11 now? But then again, I would have received many more reports from Windows 11 users...) then it is up to the user to check the Windows notifications and add the app to the "trusted apps" list, as outlined above.

Also refer to this article:

https://www.computerworld.com/article/3665694/windows-controlled-folder-access-think-twice-before-deploying.html

**Comment by till213** [comment] 2023-09-11 18:44
And this is what "ChatGPT" has to say about the topic:

https://zzzcode.ai/answer-question?id=7a954536-bfac-4829-9ae9-fd5eef044254

Pretty much sums up what I wrote above. And (except for making the app "trustworthy", which I guess means to have it digitally signed by Microsoft respectively a Certificate Authority (CA) that is trusted by Windows) there does not seem to be another (programmatic) way...

I'll investigate some more (as having a proper manifest file embedded into the executable is a good think anyway). But don't hold your breath: the above manual steps ("add Sky Dolly to the list of trusted apps that may _write_ into your documents folder) may be the final solution in the end.

**Comment by PhilM5253** [comment] 2023-09-11 21:06
Hi thanks for all of your work on this, and for your help: I hope that it has been of some use to you also!

I am sorted now: no reccordings yet (!), but SD has now created a default logbook for me on opening.

I could not make it work on a new logbook by e.g. creating then trying use a 'public' folder like C:/temp ... that still did not work.

I dont know if my 'public' folder of that type is somehow still protected? But it still looked like SD wasn't even creating the new log file, as the Win 11 save dialogue box could not 'see' a file to save?

But I have added SD as my first item on a list to 'add an allowed app' 'through controlled folder access' in Win 11.

Making this change and then starting SD has created the log file, and I now have an active (not greyed out) 'record' button within the SD UI.

Now I just need to make the time to do some MSFS flying, and record it!

Thanks again for your help, and for making SD in the first place.

**Comment by PhilM5253** [comment] 2023-09-11 21:55
I now have my first recording ... brilliant!

**Comment by PhilM5253** [comment] 2023-09-12 20:26
Thanks for the clarifications / confirmations, and thanks again for your help and support.

**Comment by till213** [comment] 2023-10-15 19:35
I am now closing this issue, with the following summary:

- The isssue seems to have been caused by the "protected folders" feature of Windows 10/11
- When "proteced folders" are enabled only code-signed applications are allowed to modify ("write") files in the documents folder
- A code-signing certificate costs money (as outlined above) and needs to be renewed every other year or so: this is currently "out of budget" for Sky Dolly
- Workaround: add an exception for Sky Dolly in the "protected folders" Windows settings

**Closed by till213** 2023-10-15 19:35 UTC
Labels: bug
