### ISSUE TITLE
Gear state not changing

### ISSUE THREAD

**Issue by jrfcs** [till213/SkyDolly#14] opened 2021-12-12 19:04 UTC
**Describe the bug**
When loading a recorded flight of Boeing Super Hornet, the gear state did not change in the model during playback.   Skydolly was setup to record during a takeoff where the gear was raised.    I stopped the recording and played back the flight.   Gear handle position went up but not the gear.  It could be a MSFS issue.

**To Reproduce**
1. start a free flight of Boeing Super Hornet
2. start recorder on skydolly
3. takeoff and raise gear
4. Stop and replay using skydolly.

**Expected behavior**
Gear to go up.

**Screenshots**

**Application version:**
v0.8.5a

**Comment by till213** [comment] 2021-12-16 10:32
Hello,

Thank you for your report. Unfortunately - or luckily, depending on the point of view - I was not able to reproduce this issue: both the landing gear lever in the cockpit and the landing gear (as seen from an external aircraft view) were raised. Repeatedly (even when "scrubbing" on the replay timeline in Sky Dolly).

I tried both a "Free flight" directly from a runway (LOWW - but I don't think the airport matters) and from a "cold and dark" start from the same airport (running the checklist automatically).

Do you happen to have any "hardware" (throttle or joystick with programmable buttons, a console...) with a "two state" button (e.g. such "two/multiple state buttons/switches" exist on my Hotas Warthog Throttle)? I am asking because maybe you have the gear state assigned to one of those multi-state buttons (switches) and during replay the state of that switch is "gear lowered"?

Alternatively you could also download the Microsoft SDK (via the "developer" mode in FS 2020, there exists a menu entry to download the SDK) and try with the "Simvar Watcher" example program, which by default is located here:

C:\MSFS SDK\Samples\SimvarWatcher\bin\x64\Release\Simvars.exe

The corresponding simulation variable which controls the gear up/down state is called "Gear Handle Position" (pro tip: the tooltips in Sky Dolly reveal the corresponding simulation variable name, in the "Simulation Variables" dialog (press key V)).

Once the flight is started and Simvars.exe is running:

* Click on Connect (a green light should indicate a successful connection)
* In the Simvar Name dropdown list, locate and select the GEAR HANDLE POSITION simulation variable
* In the Units dropdown list, select Bool or Boolean (both work - Number also always works)
* Click on the "Add request" button (the variable should now appear in the list, together with its current state, either 0.0 or 1.0)
* Now in the Value field enter a value like 1.0 (lowered) or 0.0 (raised), depending on the current state
* Click the "Try set value" button (You best try this while airborne ;))
* In FS 2020, the gear should now be lowered or raised accordingly

By the way, I tried this with the "Boeing F/A 18E Super Hornet Asobo" (in other words: the one which came for free with the latest FS 2020 update), with the default livery and no add-ons installed (especially no add-ons related to the stock F/A 18).

I will close this issue for now, but please feel free to open it again in case you have further findings which help me to actually reproduce this issue.

**Closed by till213** 2021-12-16 10:32 UTC

**Comment by till213** [comment] 2021-12-16 10:33
Just for the record: I am happy to declare that also the arrestor hook and the wing folding state are properly recorded and replayed with the Asobo F/A 18 - that was one of the first things that I've tried with Sky Dolly once the F/A 18 was available :)

**Comment by till213** [comment] 2021-12-16 10:38
And to clarify what I've meant with those "multi-state buttons/switches": Sky Dolly does "freeze" the "user aircraft" (the one being normally controlled by the player), but from this point on then merely replays all previously recorded input/button/control/switch states of the cockpit (as can be observed in the "Simulation Variables" dialog - press key V).

Any other input coming from some "control hardware" (again, I am especially referring to "multi-state switches" - and I do speak from experience with my Thrustmaster Hotas Warthog throttle where one multi-state switch is assigned to "Battery on/off") will interfere and "win over Sky Dolly".

So if Sky Dolly _once_ says "gear up" (note that variables are only sent to FS 2020 in case their recorded state actually changes) but another hardware _constantly_ says "gear down" then the gear will remain down.

**Comment by jrfcs** [comment] 2021-12-16 10:45
Thank you checking it out and the thorough explanation.   Subsequent testing for me at least showed it works on the first replay but starts going wonky after the replay is over and aircraft hits the ground or crashes (crash detection turned off).   It stops working right until I restart the MSFS program.   Also, I have the steam version of the simulator.  Don’t know if that has something to do with it.

you can close issue but by the way, if you are able can you post a fltrec file and it’s Csv of an F-18 flight you used.   I would like to try your file out.  Thanks.

**Comment by till213** [comment] 2023-01-29 14:17
The freshly released v0.14 has improved support for 3rd-party aircraft, specifically for gears, flaps and spoilers and other controls (but not everything is working perfectly yet, depending on the aircraft and its specific simulation logic).

**Comment by felipebutcher** [comment] 2023-01-29 21:59
Hi there! Thank you very much for this. I tried with the PMDG 737 and looks like everything is working (flaps, landing gear, airspeed brake). Very nice.

I only found a small issue. Tried recording 3 landings and it happened all the 3 times. There's a small lag right when the airplane is going to touch the ground. I've looked the generated sqlite db and found this little gap (~500) between two timestamps right when attitude becomes close to the airport attitude. Looks like the difference between all the timestamps are usually around 30. Not sure if that's the issue but just fyi.

Here is a recorded video where you can see the touchdown lag: https://drive.google.com/file/d/1T65WlKZ61qb9W-ytLkf2i5rH_-SnBzr9/view?usp=sharing

And here's a screenshot of the db, as you can see the gap between 30807 and 30808 is bigger than the others.

![Capture](https://user-images.githubusercontent.com/4549278/215357850-28b64fd4-6f6f-4de1-8a84-b5866b98217b.PNG)
