### ISSUE TITLE
démarrage 

### ISSUE THREAD

**Issue by Skreaz14** [till213/SkyDolly#12] opened 2021-08-07 18:05 UTC
"no valid connection plugin has been found in the plugin directory sky dolly will launch with reduced functionality"

this is the error message i get when i open it someone could help me ??

**Comment by till213** [comment] 2021-08-07 22:06
Did you create a shortcut to SkyDolly.exe? If so, make sure that the current working directory points to the folder where SkyDolly.exe is located: Sky Dolly searches for its plugins relative to its folder, in the Plugins directory: if it does not find any plugins (the plugin folder itself) then you get the message you just described.

Does it work when you directly double-click on SkyDolly.exe? If not, can you post a screenshot of the folder, including all subfolders expanded?

**Comment by Skreaz14** [comment] 2021-08-08 08:59
no I have not created a shortcut to SkyDolly.exe but if I understand correctly you have to put the plugin folder in comunity
? and when I double click on sky dolly I have the error message and one more question what are the subfolders? thank you for helping me.

**Comment by till213** [comment] 2021-08-08 09:56
„you have to put the plugin folder in comunity“

No, no, no ;) Sky Dolly operates completely independent from FS 2020 (it communicates via the official „SimConnect API“ which allows communication „from app to app“) and there is absolutely no need to modify any FS 2020 files or folders.

Once I am back home I will double-check the distributed ZIP archive and will attach a screenshot of the expected folders and files.

There are basically three scenarios where a plugin cannot be found:

- „The Obvious“

The plugin cannot be found. It is expected to be in:

Sky Dolly
+- Plugins
    +- Connect
        +- FS2020SimConnect.dll

(The plugin name could be slightly different)

Does that file exist?

- The plugin does not find its dependencies

Specifically the SimConnect.dll should be located in the Sky Dolly folder


If you have extracted the ZIP archive then all those folders - and „subfolders“ = „folder within folder“ - should be present as described

- Everything else

The file(s) could be corrupted (during download), missing permissions, some virus scanner which prevents the „dynamic loading of DLLs“ - anything really.

So let‘s hope the problem is one of #1 or #2.

If you could attach a screenshot of the entire Sky Dolly folder structure („Details“ view in File Explorer) that would be helpful already.

**Comment by till213** [comment] 2021-08-08 10:01
Oh, and to establish the extremely obvious: you _did_ unzip the downloaded ZIP archive, correct?

**Comment by Skreaz14** [comment] 2021-08-08 10:48
I have the archive I extracted with Winrar

**Comment by Skreaz14** [comment] 2021-08-08 10:49
![SkyDolly-v0 8 4 08_08_2021 14_48_41](https://user-images.githubusercontent.com/88593961/128629433-efa640d6-8883-4962-b4f0-98cc23776d32.png)

**Comment by Skreaz14** [comment] 2021-08-08 10:50
![Plugins 08_08_2021 14_49_46](https://user-images.githubusercontent.com/88593961/128629463-bc47c770-6d5c-4b61-8092-eaa4581923f2.png)
![Plugins 08_08_2021 14_50_02](https://user-images.githubusercontent.com/88593961/128629468-6452fd98-06ec-4968-9023-699dc9130d8f.png)
![Plugins 08_08_2021 14_50_08](https://user-images.githubusercontent.com/88593961/128629474-f9f9678f-a6a7-4445-b30a-13deb1a50811.png)
![Plugins 08_08_2021 14_50_12](https://user-images.githubusercontent.com/88593961/128629477-285a0de9-91cd-41e1-b5aa-e40279d9e9cc.png)

**Comment by Skreaz14** [comment] 2021-08-08 10:51
Here are the captures of the subfolder and the folder

**Comment by Skreaz14** [comment] 2021-08-08 10:53
but i think all is good all sound file present. but I had also had a problem with the flight recorder software which told me "cannot initializ SimConnect" the problem may be directly from simconnect?

**Comment by till213** [comment] 2021-08-08 14:26
Hello,

Thank you so much for providing all the screenshots! They confirm that all files are present and located in the expected folders. The file sizes also correspond to what I see.

So we can rule out "The Obvious" issue, and go to the next "The plugin does not find its dependencies" point:

"but I had also had a problem with the flight recorder software which told me "cannot initializ SimConnect" the problem may be directly from simconnect?"

Now this is very interesting, and could be connected: as I've mentioned already the communication with Flight Simulator 2020 (FS 2020) happens via the official "SimConnect API". Microsoft therefore provides a SimConnect.dll to which each "client" (= the application) connects and communicates to the "server" (= FS 2020).

This SimConnect.dll is located in the "top-level" Sky Connect folder (together with the SkyConnect.exe), and I can see it on your screenshots. And the Sky Dolly "FS2020SimConnect" plugin (the one located under Plugins/Connect) of course requires this SimConnect.dll (among other, Sky Dolly specific libraries, such as Kernel.dll, Model.dll etc.).


Now here is a possible problem: the way "DLLs" (dynamically loaded libraries") are located at runtime is influenced by quite a lot of factors, that is, Windows (the operating system) has many "[search paths](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order)" on which dependencies are searched for (some developers also call it the "[DLL hell](https://en.wikipedia.org/wiki/DLL_Hell)" ;)).

Now the _first_ location (also refer to "Standard Search Order for Desktop Applications" in [Dynamic-Link Library Search Order](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order)) should actually be the "the directory from which the application loaded" - and that is the directory where SkyDolly.exe is located in. And the mentioned SimConnect.dll - so it _should_ be found there (first).

Another location is which (last) searched is the PATH environment variable (e.g. click on the Windows "Start" menu, type "env" - you should see an entry like "Change user environment variables" - that's where all your (user-specific) variables get defined).

Again, according to the specs the PATH environment should be checked last. But it could - somehow - be that an existing SimConnect.dll is "pulled in first", but one which is incompatible with how Sky Dolly (and all its libraries and plugins) is compiled and "linked".

Admitedly that is a very weak theory - but maybe you remember having installed another FS 2020 addon / extension app which might have installed its own SimConnect.dll variant somewhere?



Another possibility is that the SimConnect.dll itself causes an error "upon initialisation" (when it is "linked" respectively "loaded"): SimConnect.dll normally communicates with the "server" (= FS 2020) via what is known as "[pipes](https://docs.microsoft.com/en-us/windows/win32/ipc/pipes)" (essentially a temporary "file" - at least conceptionally).

Now it could (again, theoretically - I am just gathering some potential pitfalls, "brainstorming" so to speak...) be that the creation of such a pipe requires special user access rights (usually that should not be a problem though), or that some "firewall" or "virus scanner" is preventing such an operation. Do you have any such 3rd party virus/firewall products installed and active?

Note that the "stock Windows internal firewall and anti-virus" applications (= the ones coming with Windows by default) should be fine: I have both (firewall and anti-virus) activated, too.


Next, there is a "Ransomware Protection" under Windows: this "Ransomware Protection" requires explicit permission for each application to "write and modify in selected user folders" (the idea is to prevent that "ransomware" encrypts all your user data and then asks for bitcoins or similar in exchange for a (promised) key".

Maybe your "Ransomware Protection" settings prevent SimConnect.dll to create the required "pipe"?



You see, I am kind of "at a loss of ideas" what could _really_ be the problem here! One last thing that comes to mind could be a problem with "path names" itself. I think you have a French localised Windows, so maybe there is a bug in Sky Dolly which fails to properly parse the path to the plugin folder. What you could try (to prove or disprove this theory) is to move the Sky Dolly folder directly into the C:\ (or D:\ - to any "top-level directory) directory, as in:

  C:\Sky Dolly\

Like this the plugin path would not contain any "strange characters" - again, I expect it to work even with blanks and non-latin charaters (any valid Windows paths characters), but it is worth a try.


Oh, and one last think which could be helpful in identifying the root cause here: do you have the "CSV" import plugin?

![grafik](https://user-images.githubusercontent.com/1205514/128635327-0de99b7f-4507-449c-bdb5-038d831b2614.png)

(The "Export" plugins only become available once you have loaded a Flight - and that requires a recorded flight which requires the FS2020SimConnectPlugin - so that would be normal (like in the screenshot) that this menu is disabled)

* Because if you do have the CSV import plugin, that would mean that the plugin loading mechanism works per se, and that the problem is really specific to the SimConnect based plugin
* But if you don't even have the CSV import plugin (as seen in the screenshot) then we know that something with the plugin loading mechanism (e.g. the plugin directory path cannot be properly found etc.) itself is fundamentally broken

**Comment by Skreaz14** [comment] 2021-08-08 14:52
![Sky Dolly 08_08_2021 18_52_44](https://user-images.githubusercontent.com/88593961/128636270-33e631f7-c0c5-4c3b-9072-f1966fbd0ff3.png)

**Comment by Skreaz14** [comment] 2021-08-08 15:01
![Élément introuvable 08_08_2021 19_00_40](https://user-images.githubusercontent.com/88593961/128636520-033b5d02-efb8-4d40-ad55-22c5f194a314.png)

**Comment by Skreaz14** [comment] 2021-08-08 15:05
when i search for simconnect it tells me that there is no longer is there a coincidence that i can't record and also when i run sky dolly and i go to "import i have the CSV import plugin I think I would have to reinstall simconnect?

**Comment by till213** [comment] 2021-08-08 20:08
Okay, so I understand:

- The CSV import plugin actually does show up

This is good news: because we can rule out any problems with the „plugin path“ and the way plugiins are loaded in Sky Dolly.

That also means that the problem really seems to be specific to the FS2020SimConnect plugin (that is my development) respectively the underlying SimConnect.dll (which comes from the MSFS 2020 SDK - „Software Development Kit“.

Now there should not be a need to „install“ SimConnect, because that SimConnect.dll typically simply comes with the actual „client“ application, like with Sky Dolly and also Flight Recorder. And that is basically all there is.

HOWEVER… (and I think we are coming closer to the problem now): client applications (like Sky Dolly) can be configured in order how they communicate with the „server“: the default (if not configured) is a „local communication“ (that means: both client and server processes (apps) run on the same machine), by creating a „pipe“ (I‘ve mentioned that).

But one can also configure a UDP or TCP connection. Why is that useful? Because the client and server can then run on different (Windows only) machines! „Networking“, in other words.

And how are client - and server - configured? Exactly! With configuration files in CFG (client) and XML (sic!) format for the server.

Also refer to the official documentation:

https://docs.flightsimulator.com/html/index.htm#t=Programming_Tools%2FSimConnect%2FSimConnect_CFG_Definition.htm

https://docs.flightsimulator.com/html/index.htm#t=Programming_Tools%2FSimConnect%2FSimConnect_XML_Definition.htm

(Btw this way of „network communication“ has been declared „legacy“ („to be removed at some point“) by Asobo / MS - but this just as a side-note).

NOW: In your case there seems to be an XML file („server configuration“) located somewhere on your computer - or there was („introuvable“). I mean, I understand a bit French, but I am not quite sure what the message is trying to say here respectively how it was produced exactly (is that some kind of „search result“? But why would the message then say „Cannot find file X“?)

In any case: it seems that - somehow - such a „SimConnect server“ configuration (XML) file was once created on your computer. And this configuration (possibly there are also some „client configuration“ (CFG) files on your computer) is causing trouble for other apps which try to connect via SimConnect.

Did you install any other FS 2020 addons in the past? Note that also „3rd party aircrafts“ can make use of SimConnect (however they usually communicate „directly“ with FS 2020, as they run „in the same process anyway“), so that XML file could have also been created by such an aircraft addon (or any addon, for that matter).

So you need to either „get rid“ of all those configuration files (in case you have no idea how they got onto your computer), or try to figure out what application (or addon) introduced them, and perhaps try to „repair“ those settings (make sure that they are „readable“).

Let me know if that helped.

**Comment by till213** [comment] 2021-08-08 20:21
Btw the „last modified date“ (10/07/2021) and perhaps also the location (D:\WpSystem\…) give you a clue how (what application/addon/…) that „SimConnect server configuration file“ got onto your computer.

**Comment by till213** [comment] 2021-08-11 15:46
Did you find a solution respectively did you find out how those XML SimConnect configuration file came onto your computer (by what application or addon)?

You may also try with the "Simvar Watcher" example application which comes with the MSFS SDK:

* In FS 2020, enable "developer mode"
* Somewhere in the developer menu there is a "Download SDK" link
* Install the downloaded SDK
* Launch C:\MSFS SDK\Samples\SimvarWatcher\bin\x64\Release\Simvars.exe

(You may notice that the exact same SimConnect.dll is located in that directory, just like with Sky Dolly; or in other words: both applications communicate with FS 2020 in the exact same way, "over the SimConnect API".)

Once you have a running FS 2020 and an active flight you can "connect" the Simvar Watcher application with FS 2020. Then add any simulation variables together with an appropriate "unit" ("number" always works) in order to "watch the values change").

The point here is of course: if not even this simple example application launches or successfully connects with FS 2020 then there is really a problem with SimConnect on your computer. But with this little example app it _might_ be easier to figure out what it is.

Not exactly a "manual", but here is a quick "dive into" how the Simvar Watcher app works:

https://forums.flightsimulator.com/t/all-simulation-events-considered-legacy/372991/8?u=steeler2340

**Comment by Skreaz14** [comment] 2021-08-11 16:54
![Release 11_08_2021 20_52_48](https://user-images.githubusercontent.com/88593961/129070703-6b5ee8ea-edc7-4ff0-9bb8-e25c0a8641c6.png)

**Comment by till213** [comment] 2021-08-12 06:37
Yes, that is the Simvar Watcher example application. I was hoping that you would at least get some kind of error message during launch which would at least hint at what the actual problem was.

But it essentially underlines what we already know: that on your computer there is a problem with starting SimConnect applications. :/

Now I am running out of ideas, so here are some ideas that I would personally try next, in ascending order of "desperation":

* Again, try to figure out how the SimConnect.xml (and possibly other files, such as a client SimConnect.cfg configuration file) came onto your computer, in around July 2021 ("last modified date")
* Once you have figured out which application (or addon) installed those SimConnect related configuration files, either try to "fix" the installation (in case it is "corrupt"), or try to completely remove any related files of that installation
* Try creating another Windows user account: if you can launch a SimConnect based application (like the above Simvar Watcher) under a new account, then you know that you have "user-specific settings" which prevent the launch of SimConnect with your original Windows user account
* If that is the case, try to find those "user-specific settings" (e.g. check your user environment variables, the registry (run regedit.exe, search for "SimConnect" or the like...)
* If found, fix or remove them
* Try searching the internet with "cannot start simconnect application" or the like
* Try in the FS forum here: 

https://forums.flightsimulator.com/c/self-service/pc-hardware/

or 

https://forums.flightsimulator.com/c/community/general-discussion-feedback/

* Try removing all your FS 2020 addons (with their official "uninstaller", if they have one - otherwise it is pointless, as you might miss "the important configuration files")
* Search your "application configuration files" user folder: C:\Users\[Your Username]\AppData (that folder is "hidden" by default: make it visible with "Show hidden files" in the File Explorer) and see whether you find any "suspicious configuration files"
* Re-install your entire operating system and all user applications (hint: you may copy the FS 2020 installation folders onto a USB stick first, so you don't have to download the entire scenery data etc. again upon installation - you should be able to simply "cancel" the download process during installation, copy the scenery etc. files back from your USB stick and continue with the installation. The installer should then recognise the "already downloaded packages")

That's about it that comes to mind. I am sorry for not being able to help more, but I am not _that_ familiar with "how SimConnect can be (mis-)configured on a global level". Actually the client configurations ("How the client tries to connect with the server"), SimConnect.cfg, are typically placed into the folder of the application itself (at the same level where the SimConnect.dll client library is), and hence should be _application specific_.

But in your case it really seems that there is something "globally" (sytem-wide) preventing the successful initialisation of the SimConnnect.dll client library - and what that could be I have no idea. Except that the existence of your mentioned "SimConnect.xml" (which is actually a server configuration file: "How the server _expects_ (or _accepts_) connections" - again, refer to the official documentation links I gave you above) could be an _indication_ to the root cause.

I will hence close this issue as "local installation problem" issue, but feel free to come back with any further questions or findings that you may have!

**Closed by till213** 2021-08-12 06:37 UTC
Labels: question
